[env]
TERM = "xterm-256color"

[font.normal]
family = "MesloLGS NF"

[terminal.shell]
program = "tmux"
args = "attach"

[general]
import = [
    "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
]
