[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[terminal.shell]
program = "/bin/zsh"

[general]
import = [
    "~/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"
]
